#!/bin/bash

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [[ "$current_branch" = "master" ]] && [[ -n "$(git diff --exit-code index.html)" ]]; then
  echo "Pushing index.html to mon-oren-bucket"
  aws s3 cp "$PWD"/index.html s3://mon-oren-bucket
fi
